### Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([10,20,40,70,80,0])

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(6,)

In [5]:
a.ndim

1

In [6]:
a.size

6

In [7]:
a[0]

10

In [8]:
a[4]

80

### Multi dimensional array

In [9]:
a_2nd=np.array([[10,30,40], [22,34,18]])

In [10]:
a_2nd

array([[10, 30, 40],
       [22, 34, 18]])

In [11]:
a_2nd.dtype

dtype('int32')

In [12]:
a_2nd.shape

(2, 3)

In [13]:
a_2nd.ndim

2

In [14]:
a_2nd[1]

array([22, 34, 18])

### Another type of multi dimensional arrays

In [15]:
another_type_array=np.array([[(2,3,5,6,7)]])

In [16]:
another_type_array

array([[[2, 3, 5, 6, 7]]])

In [17]:
another_type_array.shape

(1, 1, 5)

In [18]:
another_type_array.ndim

3

#### First element in first array 

In [19]:
a_2nd[0][0]

10

#### Second element in second array 

In [20]:
a_2nd[1][1]

34

#### Lets change its data type into float

In [21]:
a_2nd=np.array([[10,30,40], [22,34,18]], dtype=float)

In [22]:
a_2nd

array([[10., 30., 40.],
       [22., 34., 18.]])

#### Lets create a bigger array 

In [23]:
a_bigger=np.array([
[
[12,22,33,46],[5,4,7,3],[2,2,2,3]
],
[
[7,8,4,28],[2,3,3,4],[3,0,0,1]
],
[
[12,36,42,4],[24,2,12,3],[0,2,4,1]
]
], dtype = float )

In [24]:
a_bigger.shape

(3, 3, 4)

In [25]:
a_bigger.ndim

3

In [26]:
a_bigger.size

36

In [27]:
a_bigger[2][2][3]

1.0

In [28]:
a_bigger[2][2]

array([0., 2., 4., 1.])

#### Filling arrays

In [29]:
a_full=np.full((4,5,6),6)

In [30]:
a_full

array([[[6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6]],

       [[6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6]],

       [[6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6]],

       [[6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6, 6]]])

In [31]:
a_full.ndim

3

#### ZEROS AND ONES

In [33]:
a_zeros=np.zeros((4,4))
a_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
b_ones=np.ones((3,3,4))
b_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [35]:
b_ones.ndim

3

#### EMPTY AND RANDOM

In [36]:
e=np.empty((3,4))
e

array([[1.12981944e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.14587773e-312, 7.26815049e-043, 2.46414801e+184,
        2.46705299e+184],
       [1.68718528e-051, 8.60992800e-043, 1.16413631e+165,
        3.69411897e-057]])

In [37]:
b_random=np.random.random((2,2))
b_random

array([[0.99796913, 0.06334057],
       [0.69497682, 0.15240879]])

In [38]:
b_random.ndim

2

In [39]:
b_random.size

4

### RANGES

#### Arange

In [40]:
a_arange=np.arange(10,50,5)

In [41]:
a_arange

array([10, 15, 20, 25, 30, 35, 40, 45])

#### linspace

In [49]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [52]:
np.random.rand(2)

array([0.88736104, 0.73934936])

In [53]:
b_linspace=np.linspace(0,50,2)
b_linspace

array([ 0., 50.])

In [54]:
b_linspace1=np.linspace(0,50,35)

In [55]:
b_linspace1

array([ 0.        ,  1.47058824,  2.94117647,  4.41176471,  5.88235294,
        7.35294118,  8.82352941, 10.29411765, 11.76470588, 13.23529412,
       14.70588235, 16.17647059, 17.64705882, 19.11764706, 20.58823529,
       22.05882353, 23.52941176, 25.        , 26.47058824, 27.94117647,
       29.41176471, 30.88235294, 32.35294118, 33.82352941, 35.29411765,
       36.76470588, 38.23529412, 39.70588235, 41.17647059, 42.64705882,
       44.11764706, 45.58823529, 47.05882353, 48.52941176, 50.        ])

In [56]:
b_linspace1.size

35

In [58]:
b_linspace2=np.linspace(0,50,30, dtype=int)
b_linspace2

array([ 0,  1,  3,  5,  6,  8, 10, 12, 13, 15, 17, 18, 20, 22, 24, 25, 27,
       29, 31, 32, 34, 36, 37, 39, 41, 43, 44, 46, 48, 50])